id: P2E12FFCD
initial_creation_type: ocr
source_metadata:
  volumes:
    46e01ab5316244b4bca1178d5497542d:
      base_file: v013.txt
      image_group_id: I1PD95858
      title: དཔལ་གདན་བཞི་པའི་ཟབ་དོན་སྟོན་པ་ཤིང་གཅིག་གི་དཀའ་འགྲེལ།
      total_pages: 2043
      volume_number: 13
